//
// File generated by /b/root-5.27.02//bin/rootcint at Wed Jun 30 00:43:46 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "guiDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void my1_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_my1(void *p = 0);
   static void *newArray_my1(Long_t size, void *p);
   static void delete_my1(void *p);
   static void deleteArray_my1(void *p);
   static void destruct_my1(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::my1*)
   {
      ::my1 *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::my1 >(0);
      static ::ROOT::TGenericClassInfo 
         instance("my1", ::my1::Class_Version(), "./test.h", 6,
                  typeid(::my1), DefineBehavior(ptr, ptr),
                  &::my1::Dictionary, isa_proxy, 4,
                  sizeof(::my1) );
      instance.SetNew(&new_my1);
      instance.SetNewArray(&newArray_my1);
      instance.SetDelete(&delete_my1);
      instance.SetDeleteArray(&deleteArray_my1);
      instance.SetDestructor(&destruct_my1);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::my1*)
   {
      return GenerateInitInstanceLocal((::my1*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::my1*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *my1::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *my1::Class_Name()
{
   return "my1";
}

//______________________________________________________________________________
const char *my1::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::my1*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int my1::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::my1*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void my1::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::my1*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *my1::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::my1*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void my1::Streamer(TBuffer &R__b)
{
   // Stream an object of class my1.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(my1::Class(),this);
   } else {
      R__b.WriteClassBuffer(my1::Class(),this);
   }
}

//______________________________________________________________________________
void my1::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class my1.
      TClass *R__cl = ::my1::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_my1(void *p) {
      return  p ? new(p) ::my1 : new ::my1;
   }
   static void *newArray_my1(Long_t nElements, void *p) {
      return p ? new(p) ::my1[nElements] : new ::my1[nElements];
   }
   // Wrapper around operator delete
   static void delete_my1(void *p) {
      delete ((::my1*)p);
   }
   static void deleteArray_my1(void *p) {
      delete [] ((::my1*)p);
   }
   static void destruct_my1(void *p) {
      typedef ::my1 current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::my1

/********************************************************
* guiDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableguiDict();

extern "C" void G__set_cpp_environmentguiDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("test.h");
  G__cpp_reset_tagtableguiDict();
}
#include <new>
extern "C" int G__cpp_dllrevguiDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* my1 */
static int G__guiDict_202_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   my1* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new my1[n];
     } else {
       p = new((void*) gvp) my1[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new my1;
     } else {
       p = new((void*) gvp) my1;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__guiDictLN_my1));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__guiDict_202_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((my1*) G__getstructoffset())->call1();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__guiDict_202_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((my1*) G__getstructoffset())->callshot();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__guiDict_202_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) my1::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__guiDict_202_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) my1::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__guiDict_202_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) my1::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__guiDict_202_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      my1::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__guiDict_202_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((my1*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__guiDict_202_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) my1::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__guiDict_202_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) my1::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__guiDict_202_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) my1::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__guiDict_202_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) my1::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__guiDict_202_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   my1* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new my1(*(my1*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__guiDictLN_my1));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef my1 G__Tmy1;
static int G__guiDict_202_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (my1*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((my1*) (soff+(sizeof(my1)*i)))->~G__Tmy1();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (my1*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((my1*) (soff))->~G__Tmy1();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__guiDict_202_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   my1* dest = (my1*) G__getstructoffset();
   *dest = *(my1*) libp->para[0].ref;
   const my1& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* my1 */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncguiDict {
 public:
  G__Sizep2memfuncguiDict(): p(&G__Sizep2memfuncguiDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncguiDict::*p)();
};

size_t G__get_sizep2memfuncguiDict()
{
  G__Sizep2memfuncguiDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceguiDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__guiDictLN_my1))) {
     my1 *G__Lderived;
     G__Lderived=(my1*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__guiDictLN_my1),G__get_linked_tagnum(&G__guiDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableguiDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__guiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__guiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__guiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__guiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__guiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__guiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__guiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__guiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__guiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__guiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* my1 */
static void G__setup_memvarmy1(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__guiDictLN_my1));
   { my1 *p; p=(my1*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__guiDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarguiDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncmy1(void) {
   /* my1 */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__guiDictLN_my1));
   G__memfunc_setup("my1",279,G__guiDict_202_0_1, 105, G__get_linked_tagnum(&G__guiDictLN_my1), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("call1",461,G__guiDict_202_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("callshot",858,G__guiDict_202_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__guiDict_202_0_4, 85, G__get_linked_tagnum(&G__guiDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&my1::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__guiDict_202_0_5, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&my1::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__guiDict_202_0_6, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&my1::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__guiDict_202_0_7, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&my1::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__guiDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__guiDict_202_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__guiDict_202_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&my1::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__guiDict_202_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&my1::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__guiDict_202_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&my1::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__guiDict_202_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&my1::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("my1", 279, G__guiDict_202_0_16, (int) ('i'), G__get_linked_tagnum(&G__guiDictLN_my1), -1, 0, 1, 1, 1, 0, "u 'my1' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~my1", 405, G__guiDict_202_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__guiDict_202_0_18, (int) ('u'), G__get_linked_tagnum(&G__guiDictLN_my1), -1, 1, 1, 1, 1, 0, "u 'my1' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncguiDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalguiDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcguiDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__guiDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__guiDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__guiDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__guiDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__guiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__guiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__guiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__guiDictLN_my1 = { "my1" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableguiDict() {
  G__guiDictLN_TClass.tagnum = -1 ;
  G__guiDictLN_TBuffer.tagnum = -1 ;
  G__guiDictLN_TMemberInspector.tagnum = -1 ;
  G__guiDictLN_TObject.tagnum = -1 ;
  G__guiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__guiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__guiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__guiDictLN_my1.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableguiDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__guiDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__guiDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__guiDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__guiDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__guiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__guiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__guiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__guiDictLN_my1),sizeof(my1),-1,292096,(char*)NULL,G__setup_memvarmy1,G__setup_memfuncmy1);
}
extern "C" void G__cpp_setupguiDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupguiDict()");
  G__set_cpp_environmentguiDict();
  G__cpp_setup_tagtableguiDict();

  G__cpp_setup_inheritanceguiDict();

  G__cpp_setup_typetableguiDict();

  G__cpp_setup_memvarguiDict();

  G__cpp_setup_memfuncguiDict();
  G__cpp_setup_globalguiDict();
  G__cpp_setup_funcguiDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncguiDict();
  return;
}
class G__cpp_setup_initguiDict {
  public:
    G__cpp_setup_initguiDict() { G__add_setup_func("guiDict",(G__incsetup)(&G__cpp_setupguiDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initguiDict() { G__remove_setup_func("guiDict"); }
};
G__cpp_setup_initguiDict G__cpp_setup_initializerguiDict;

