/********************************************************************
* guiDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error guiDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableguiDict();
extern void G__cpp_setup_inheritanceguiDict();
extern void G__cpp_setup_typetableguiDict();
extern void G__cpp_setup_memvarguiDict();
extern void G__cpp_setup_globalguiDict();
extern void G__cpp_setup_memfuncguiDict();
extern void G__cpp_setup_funcguiDict();
extern void G__set_cpp_environmentguiDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "test.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__guiDictLN_TClass;
extern G__linked_taginfo G__guiDictLN_TBuffer;
extern G__linked_taginfo G__guiDictLN_TMemberInspector;
extern G__linked_taginfo G__guiDictLN_TObject;
extern G__linked_taginfo G__guiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__guiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__guiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__guiDictLN_my1;

/* STUB derived class for protected member access */
